table clients
	lineageTag: 35cb78fc-8f24-4d11-a650-dd2d473b4764

	column client_id
		dataType: string
		lineageTag: 8b8e6a48-a722-4caa-8484-68303d6c85a8
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 1608c20a-cd5f-4fd6-b23c-4dfcff268169
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 95dfb445-4d4f-4016-b4fd-5419bb1e09ef
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column preferred_language
		dataType: string
		lineageTag: 17224f80-11cf-4576-acec-b133c8afa514
		summarizeBy: none
		sourceColumn: preferred_language

		annotation SummarizationSetBy = Automatic

	column account_open_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a341d741-b249-4ac4-b5f3-eec7206d34ff
		summarizeBy: none
		sourceColumn: account_open_date

		variation Variation
			isDefault
			relationship: 88eec9af-4123-4e2c-877f-aacf05df8a0c
			defaultHierarchy: LocalDateTable_73e59545-ba3b-4186-9467-88043cbeabc1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column client_status
		dataType: string
		lineageTag: 57d82f31-6699-441a-a215-2c362f205a86
		summarizeBy: none
		sourceColumn: client_status

		annotation SummarizationSetBy = Automatic

	column client_segment
		dataType: string
		lineageTag: d8dea082-544b-4af5-9187-1503a97edf8b
		summarizeBy: none
		sourceColumn: client_segment

		annotation SummarizationSetBy = Automatic

	column risk_classification
		dataType: string
		lineageTag: 3e9a43cf-1196-424b-bbb0-f736800266dd
		summarizeBy: none
		sourceColumn: risk_classification

		annotation SummarizationSetBy = Automatic

	column onboarding_channel
		dataType: string
		lineageTag: 50caa9da-b606-405e-8192-ac0490761552
		summarizeBy: none
		sourceColumn: onboarding_channel

		annotation SummarizationSetBy = Automatic

	column base_currency
		dataType: string
		lineageTag: b2b195a9-1322-48d2-8a7d-6767473dbb32
		summarizeBy: none
		sourceColumn: base_currency

		annotation SummarizationSetBy = Automatic

	partition clients = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Faisa\OneDrive\Desktop\brokerage-risk-analytics-clean\outputs\powerbi\clients.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"client_id", type text}, {"country", type text}, {"region", type text}, {"preferred_language", type text}, {"account_open_date", type date}, {"client_status", type text}, {"client_segment", type text}, {"risk_classification", type text}, {"onboarding_channel", type text}, {"base_currency", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

