table instruments
	lineageTag: 37b9fc2e-b876-428e-852a-80cc36a4c706

	column instrument_id
		dataType: string
		lineageTag: c83ff708-d8b7-4c62-94c0-afa7e83b2a18
		summarizeBy: none
		sourceColumn: instrument_id

		annotation SummarizationSetBy = Automatic

	column symbol
		dataType: string
		lineageTag: 06b0c83f-71d0-431e-ae82-a0e76e291b6c
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column asset_class
		dataType: string
		lineageTag: aaf8b345-7234-4ed8-a830-fb2564247db7
		summarizeBy: none
		sourceColumn: asset_class

		annotation SummarizationSetBy = Automatic

	column contract_size
		dataType: int64
		formatString: 0
		lineageTag: 9442567b-a672-4d75-9a76-88ff2483391a
		summarizeBy: none
		sourceColumn: contract_size

		annotation SummarizationSetBy = Automatic

	column tick_size
		dataType: double
		lineageTag: 5f8c883d-da87-436a-bb30-827d14248876
		summarizeBy: none
		sourceColumn: tick_size

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trading_status
		dataType: string
		lineageTag: f0ca2454-68cd-4b2c-9375-215ef173e9e8
		summarizeBy: none
		sourceColumn: trading_status

		annotation SummarizationSetBy = Automatic

	partition instruments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Faisa\OneDrive\Desktop\brokerage-risk-analytics-clean\outputs\powerbi\instruments.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"instrument_id", type text}, {"symbol", type text}, {"asset_class", type text}, {"contract_size", Int64.Type}, {"tick_size", type number}, {"trading_status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

