table transactions
	lineageTag: 692d728b-630d-4b88-b31e-1be8aa3746c5

	column transaction_id
		dataType: string
		lineageTag: 89c6a85d-083c-4e8d-9bd1-bfc3fd11e091
		summarizeBy: none
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: string
		lineageTag: 08cda6e8-41a6-4244-9be9-fc39cc1802bf
		summarizeBy: none
		sourceColumn: client_id

		annotation SummarizationSetBy = Automatic

	column account_id
		dataType: string
		lineageTag: be40a39f-fc89-4f50-a36c-f8941cf2f109
		summarizeBy: none
		sourceColumn: account_id

		annotation SummarizationSetBy = Automatic

	column timestamp
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05bc4176-f255-45f9-bc20-cc1f41698f4e
		summarizeBy: none
		sourceColumn: timestamp

		variation Variation
			isDefault
			relationship: 176efdc6-9647-4398-99b5-0822a7af8af1
			defaultHierarchy: LocalDateTable_2ed7239f-f68a-48bd-9e5e-fce2e1959b8b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transaction_type
		dataType: string
		lineageTag: ed4e424b-2e76-4a16-9a7e-2fffea416a6f
		summarizeBy: none
		sourceColumn: transaction_type

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 4384a54c-2809-4b3c-861b-9e46a2ad2d96
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column currency
		dataType: string
		lineageTag: 622c912a-be19-4cc5-9be1-a0d585f93070
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 264ba60e-95e4-4a6f-ae65-710edd4ed41a
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column transaction_status
		dataType: string
		lineageTag: 09cc61fa-4f9d-43f3-b163-3c4dc8ab2064
		summarizeBy: none
		sourceColumn: transaction_status

		annotation SummarizationSetBy = Automatic

	column processing_fee
		dataType: double
		lineageTag: 043cea97-a784-44e1-bccc-4be27b73cbf9
		summarizeBy: sum
		sourceColumn: processing_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reference_id
		dataType: string
		lineageTag: 4b0bc505-7d92-4851-ad61-39b09d448567
		summarizeBy: none
		sourceColumn: reference_id

		annotation SummarizationSetBy = Automatic

	partition transactions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Faisa\OneDrive\Desktop\brokerage-risk-analytics-clean\outputs\powerbi\transactions.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"transaction_id", type text}, {"client_id", type text}, {"account_id", type text}, {"timestamp", type date}, {"transaction_type", type text}, {"amount", type number}, {"currency", type text}, {"payment_method", type text}, {"transaction_status", type text}, {"processing_fee", type number}, {"reference_id", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

